<?php
/**
 * @file
 * designssquare_com_theme_espresso_sample_data.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function designssquare_com_theme_espresso_sample_data_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 1,
  'title' => 'About',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '904cdff1-ee35-4528-83be-8c8de44bec3f',
  'type' => 'basic_page_3_columns',
  'language' => 'und',
  'created' => 1401023183,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '050db19b-bd85-4587-9289-7ef6bb58639c',
  'revision_uid' => 1,
  'field_column_one' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat.</p>
						<p>Nunc nec tellus sit amet leo consequat mollis eget sed urna. Aliquam pharetra sodales mattis. Phasellus semper quam tempor urna ullamcorper tristique imperdiet dui vulputate. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam auctor volutpat leo, sagittis laoreet dolor laoreet quis. Ut massa urna, varius nec placerat at, commodo ac massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec at justo in nulla egestas lobortis. Cras tristique, massa et cursus accumsan, lectus velit malesuada augue, sed tempor erat turpis ut nibh. Donec fermentum tempus ultricies. Sed pretium tincidunt imperdiet. Praesent commodo cursus neque sit amet accumsan. Duis malesuada gravida iaculis. Duis convallis sollicitudin orci, eu pulvinar augue cursus vitae. Nullam bibendum malesuada sem, id rhoncus est tristique ac.</p>
					',
        'format' => NULL,
        'safe_value' => '&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat.&lt;/p&gt;
						&lt;p&gt;Nunc nec tellus sit amet leo consequat mollis eget sed urna. Aliquam pharetra sodales mattis. Phasellus semper quam tempor urna ullamcorper tristique imperdiet dui vulputate. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam auctor volutpat leo, sagittis laoreet dolor laoreet quis. Ut massa urna, varius nec placerat at, commodo ac massa. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec at justo in nulla egestas lobortis. Cras tristique, massa et cursus accumsan, lectus velit malesuada augue, sed tempor erat turpis ut nibh. Donec fermentum tempus ultricies. Sed pretium tincidunt imperdiet. Praesent commodo cursus neque sit amet accumsan. Duis malesuada gravida iaculis. Duis convallis sollicitudin orci, eu pulvinar augue cursus vitae. Nullam bibendum malesuada sem, id rhoncus est tristique ac.&lt;/p&gt;
					',
      ),
    ),
  ),
  'field_column_two' => array(
    'und' => array(
      0 => array(
        'value' => '<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat.</p>
						<p>Ut at augue massa. Nam eget enim at eros aliquam commodo rutrum sed justo. Etiam quis eros sem. Maecenas placerat, metus eu ornare lobortis, nibh metus lacinia lorem, ut pharetra libero tellus eu massa. Fusce erat quam, eleifend ac dictum a, dictum vestibulum sapien. Nam lorem tellus, porttitor sit amet sollicitudin et, scelerisque eu nunc. Vivamus eu nunc tristique neque euismod interdum suscipit nec est. Sed tellus arcu, lacinia vitae viverra eu, vulputate eu mauris.</p>
						<p>Sed adipiscing, nibh vitae imperdiet adipiscing, orci risus porttitor dui, vel rhoncus felis ligula interdum lectus. Duis at purus tortor. Cras congue volutpat lectus, eu vestibulum risus ornare sed. Aliquam elementum porttitor leo et rutrum. Aliquam in leo ut turpis porttitor gravida vel non diam. Etiam quis diam felis. Integer dictum.
						</p>',
        'format' => NULL,
        'safe_value' => '&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat.&lt;/p&gt;
						&lt;p&gt;Ut at augue massa. Nam eget enim at eros aliquam commodo rutrum sed justo. Etiam quis eros sem. Maecenas placerat, metus eu ornare lobortis, nibh metus lacinia lorem, ut pharetra libero tellus eu massa. Fusce erat quam, eleifend ac dictum a, dictum vestibulum sapien. Nam lorem tellus, porttitor sit amet sollicitudin et, scelerisque eu nunc. Vivamus eu nunc tristique neque euismod interdum suscipit nec est. Sed tellus arcu, lacinia vitae viverra eu, vulputate eu mauris.&lt;/p&gt;
						&lt;p&gt;Sed adipiscing, nibh vitae imperdiet adipiscing, orci risus porttitor dui, vel rhoncus felis ligula interdum lectus. Duis at purus tortor. Cras congue volutpat lectus, eu vestibulum risus ornare sed. Aliquam elementum porttitor leo et rutrum. Aliquam in leo ut turpis porttitor gravida vel non diam. Etiam quis diam felis. Integer dictum.
						&lt;/p&gt;',
      ),
    ),
  ),
  'field_column_three' => array(
    'und' => array(
      0 => array(
        'value' => '<p><img src="/sites/default/files/designssquare_theme/espresso/img/bio-lg.jpg" alt="About" class="img-responsive thumbnail"></p>',
        'format' => NULL,
        'safe_value' => '&lt;p&gt;&lt;img src=&quot;/sites/default/files/designssquare_theme/espresso/img/bio-lg.jpg&quot; alt=&quot;About&quot; class=&quot;img-responsive thumbnail&quot;&gt;&lt;/p&gt;',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 1,
  'data' => 'a:2:{s:7:"contact";i:0;s:7:"overlay";i:1;}',
  'date' => '2014-05-25 13:06:23 +0000',
  'alias_url' => 'about',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Blog Posts',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'e4c6c534-9561-4383-8d4f-da1ffeade111',
  'type' => 'page',
  'language' => 'und',
  'created' => 1401029822,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '3d73a978-de73-4ef8-81df-29ed75c5dbc3',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div class="blog-post row">
					<div class="meta col-sm-3 hidden-xs">
						<dl>
							<dt><p><span class="glyphicon glyphicon-calendar"></span> Date:</p></dt>
							<dd>July 25, 2012</dd>
							<dt><p><span class="glyphicon glyphicon-list"></span> Categories:</p></dt>
							<dd><a href="categories.html">Books</a></dd>
							<dt><p><span class="glyphicon glyphicon-tag"></span> Tags:</p></dt>
							<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
						</dl>
					</div>
					<div class="entry col-sm-9">
						<h2><a href="/post">The Emerald City of Oz</a></h2>
						<p>"That is true," said the Scarecrow.  "You see," he continued confidentially, "I don\'t mind my legs and arms and body being stuffed, because I cannot get hurt.  If anyone treads on my toes or sticks a pin into me, it doesn\'t matter, for I can\'t feel it.  But I do not want people to call me a fool, and if my head stays stuffed with straw instead of with brains, as yours is, how am I ever to know anything?"</p>
						<p><a href="/post"><strong>Continue reading</strong> <span class="glyphicon glyphicon-arrow-right"></span></a></p>
						<p><span class="glyphicon glyphicon-comment"></span> <strong>17 Comments</strong></p>
					</div>
				</div>
				<div class="blog-post row">
					<div class="meta col-sm-3 hidden-xs">
						<dl>
							<dt><p><span class="glyphicon glyphicon-calendar"></span> Date:</p></dt>
							<dd>July 17, 2012</dd>
							<dt><p><span class="glyphicon glyphicon-list"></span> Categories:</p></dt>
							<dd><a href="categories.html">Books</a></dd>
							<dt><p><span class="glyphicon glyphicon-tag"></span> Tags:,</p></dt>
							<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
						</dl>
					</div>
					<div class="entry col-sm-9">
						<h2><a href="/post">Yellow Brick Road</a></h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
						<p><a href="/post><strong>Continue reading</strong> <span class="glyphicon glyphicon-arrow-right"></span></a></p>
						<p><span class="glyphicon glyphicon-comment"></span> <strong>7 Comments</strong></p>
					</div>
				</div>
				<div class="blog-post row">
					<div class="meta col-sm-3 hidden-xs">
						<dl>
							<dt><p><span class="glyphicon glyphicon-calendar"></span> Date:</p></dt>
							<dd>July 09, 2012</dd>
							<dt><p><span class="glyphicon glyphicon-list"></span> Categories:</p></dt>
							<dd><a href="categories.html">Books</a></dd>
							<dt><p><span class="glyphicon glyphicon-tag"></span> Tags:</p></dt>
							<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
						</dl>
					</div>
					<div class="entry col-sm-9">
						<h2><a href="/post">Somewhere Over The Rainbow</a></h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
						<p><a href="/post"><strong>Continue reading</strong> <span class="glyphicon glyphicon-arrow-right"></span></a></p>
						<p><span class="glyphicon glyphicon-comment"></span> <strong>3 Comments</strong></p>
					</div>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="blog-post row">
<div class="meta col-sm-3 hidden-xs">
<dl><dt>
<p><span class="glyphicon glyphicon-calendar"></span> Date:</p>
</dt>
<dd>July 25, 2012</dd>
<dt>
<p><span class="glyphicon glyphicon-list"></span> Categories:</p>
</dt>
<dd><a href="categories.html">Books</a></dd>
<dt>
<p><span class="glyphicon glyphicon-tag"></span> Tags:</p>
</dt>
<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
</dl></div>
<div class="entry col-sm-9">
<h2><a href="/post">The Emerald City of Oz</a></h2>
<p>"That is true," said the Scarecrow.  "You see," he continued confidentially, "I don\'t mind my legs and arms and body being stuffed, because I cannot get hurt.  If anyone treads on my toes or sticks a pin into me, it doesn\'t matter, for I can\'t feel it.  But I do not want people to call me a fool, and if my head stays stuffed with straw instead of with brains, as yours is, how am I ever to know anything?"</p>
<p><a href="/post"><strong>Continue reading</strong> <span class="glyphicon glyphicon-arrow-right"></span></a></p>
<p><span class="glyphicon glyphicon-comment"></span> <strong>17 Comments</strong></p>
</div>
</div>
<div class="blog-post row">
<div class="meta col-sm-3 hidden-xs">
<dl><dt>
<p><span class="glyphicon glyphicon-calendar"></span> Date:</p>
</dt>
<dd>July 17, 2012</dd>
<dt>
<p><span class="glyphicon glyphicon-list"></span> Categories:</p>
</dt>
<dd><a href="categories.html">Books</a></dd>
<dt>
<p><span class="glyphicon glyphicon-tag"></span> Tags:,</p>
</dt>
<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
</dl></div>
<div class="entry col-sm-9">
<h2><a href="/post">Yellow Brick Road</a></h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,<br />
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo<br />
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse<br />
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non<br />
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p><a href="/post&gt;&lt;strong&gt;Continue reading&lt;/strong&gt; &lt;span class=" glyphicon="" glyphicon-arrow-right=""></a></p>
<p><span class="glyphicon glyphicon-comment"></span> <strong>7 Comments</strong></p>
</div>
</div>
<div class="blog-post row">
<div class="meta col-sm-3 hidden-xs">
<dl><dt>
<p><span class="glyphicon glyphicon-calendar"></span> Date:</p>
</dt>
<dd>July 09, 2012</dd>
<dt>
<p><span class="glyphicon glyphicon-list"></span> Categories:</p>
</dt>
<dd><a href="categories.html">Books</a></dd>
<dt>
<p><span class="glyphicon glyphicon-tag"></span> Tags:</p>
</dt>
<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
</dl></div>
<div class="entry col-sm-9">
<h2><a href="/post">Somewhere Over The Rainbow</a></h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
						tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,<br />
						quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo<br />
						consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse<br />
						cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non<br />
						proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p><a href="/post"><strong>Continue reading</strong> <span class="glyphicon glyphicon-arrow-right"></span></a></p>
<p><span class="glyphicon glyphicon-comment"></span> <strong>3 Comments</strong></p>
</div>
</div>',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 1,
  'data' => 'a:2:{s:7:"contact";i:0;s:7:"overlay";i:1;}',
  'date' => '2014-05-25 14:57:02 +0000',
  'alias_url' => 'blog-posts',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Single Post',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'b07f067d-cdfe-4d6c-bb77-0c8365d9c686',
  'type' => 'page',
  'language' => 'und',
  'created' => 1401036352,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '490d0b14-bf46-4155-a8ce-65d79fc0afd4',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '				<div class="blog-post row">
					<div class="meta col-sm-2">
						<dl>
							<dt><p><i class="icon-calendar icon-white"></i> Date:</p></dt>
							<dd>July 25, 2012</dd>
							<dt><p><i class="icon-list icon-white"></i> Categories:</p></dt>
							<dd><a href="categories.html">Books</a></dd>
							<dt><p><i class="icon-tag icon-white"></i> Tags:</p></dt>
							<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
						</dl>
					</div>
					<div class="entry col-sm-10">
						<h2>The Emerald City of Oz</h2>
						<p><img src="/sites/default/files/designssquare_theme/espresso/img/birdgreen-lg.jpg" alt="Placeholder" width="154" height="100" class="right thumbnail"> "Who are you?" asked the Scarecrow when he had stretched himself and yawned.  "And where are you going?"</p>

						<p>"My name is Dorothy," said the girl, "and I am going to the Emerald City, to ask the Great Oz to send me back to Kansas."</p>

						<p>"Where is the Emerald City?" he inquired.  "And who is Oz?"</p>

						<p>"Why, don\'t you know?" she returned, in surprise.</p>

						<p>"No, indeed.  I don\'t know anything.  You see, I am stuffed, so I have no brains at all," he answered sadly.</p>

						<p>"Oh," said Dorothy, "I\'m awfully sorry for you."</p>

						<p><img src="/sites/default/files/designssquare_theme/espresso/img/flowers-lg.jpg" alt="Placeholder" width="154" height="100" class="left thumbnail">"Do you think," he asked, "if I go to the Emerald City with you, that Oz would give me some brains?"</p>

						<p>"I cannot tell," she returned, "but you may come with me, if you like. If Oz will not give you any brains you will be no worse off than you are now."</p>

						<p> "That is true," said the Scarecrow.  "You see," he continued confidentially, "I don\'t mind my legs and arms and body being stuffed, because I cannot get hurt.  If anyone treads on my toes or sticks a pin into me, it doesn\'t matter, for I can\'t feel it.  But I do not want people to call me a fool, and if my head stays stuffed with straw instead of with brains, as yours is, how am I ever to know anything?"</p>

						<p>"I understand how you feel," said the little girl, who was truly sorry for him.  "If you will come with me I\'ll ask Oz to do all he can for you."</p>
					</div>
				</div>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="blog-post row">
<div class="meta col-sm-2">
<dl><dt>
<p><i class="icon-calendar icon-white"></i> Date:</p>
</dt>
<dd>July 25, 2012</dd>
<dt>
<p><i class="icon-list icon-white"></i> Categories:</p>
</dt>
<dd><a href="categories.html">Books</a></dd>
<dt>
<p><i class="icon-tag icon-white"></i> Tags:</p>
</dt>
<dd><a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></dd>
</dl></div>
<div class="entry col-sm-10">
<h2>The Emerald City of Oz</h2>
<p><img src="/sites/default/files/designssquare_theme/espresso/img/birdgreen-lg.jpg" alt="Placeholder" width="154" height="100" class="right thumbnail" /> "Who are you?" asked the Scarecrow when he had stretched himself and yawned.  "And where are you going?"</p>
<p>"My name is Dorothy," said the girl, "and I am going to the Emerald City, to ask the Great Oz to send me back to Kansas."</p>
<p>"Where is the Emerald City?" he inquired.  "And who is Oz?"</p>
<p>"Why, don\'t you know?" she returned, in surprise.</p>
<p>"No, indeed.  I don\'t know anything.  You see, I am stuffed, so I have no brains at all," he answered sadly.</p>
<p>"Oh," said Dorothy, "I\'m awfully sorry for you."</p>
<p><img src="/sites/default/files/designssquare_theme/espresso/img/flowers-lg.jpg" alt="Placeholder" width="154" height="100" class="left thumbnail" />"Do you think," he asked, "if I go to the Emerald City with you, that Oz would give me some brains?"</p>
<p>"I cannot tell," she returned, "but you may come with me, if you like. If Oz will not give you any brains you will be no worse off than you are now."</p>
<p> "That is true," said the Scarecrow.  "You see," he continued confidentially, "I don\'t mind my legs and arms and body being stuffed, because I cannot get hurt.  If anyone treads on my toes or sticks a pin into me, it doesn\'t matter, for I can\'t feel it.  But I do not want people to call me a fool, and if my head stays stuffed with straw instead of with brains, as yours is, how am I ever to know anything?"</p>
<p>"I understand how you feel," said the little girl, who was truly sorry for him.  "If you will come with me I\'ll ask Oz to do all he can for you."</p>
</div>
</div>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 5,
  'last_comment_name' => '',
  'last_comment_uid' => 1,
  'comment_count' => 4,
  'name' => 'admin',
  'picture' => 1,
  'data' => 'a:2:{s:7:"contact";i:0;s:7:"overlay";i:1;}',
  'date' => '2014-05-25 16:45:52 +0000',
  'alias_url' => 'post',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Portfolio',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '0ba4ddab-0353-40b3-bceb-b818bdedb69a',
  'type' => 'portfolio',
  'language' => 'und',
  'created' => 1401036182,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '839271fa-3953-4798-9d97-f2c99d0def03',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdgreen-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Hummingbird Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/flowers-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Red Flowers Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/leaves-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Leaves Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/snail-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Snail Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdsepia-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Hummingbird Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/butterfly-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Butterfly Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdretro-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Retro Bird Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdfat-lg.jpg" alt="Placeholder" class="thumbnail"></a>
				<h3><a href="/project">Small Bird Project</a></h3>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua.</p>
			</div>
',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdgreen-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Hummingbird Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/flowers-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Red Flowers Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/leaves-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Leaves Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/snail-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Snail Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdsepia-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Hummingbird Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/butterfly-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Butterfly Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdretro-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Retro Bird Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
<div class="module col-sm-3 row-element">
				<a href="/project"><img src="/sites/default/files/designssquare_theme/espresso/img/birdfat-lg.jpg" alt="Placeholder" class="thumbnail" /></a>
<h3><a href="/project">Small Bird Project</a></h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua.</p>
</div>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 1,
  'data' => 'a:2:{s:7:"contact";i:0;s:7:"overlay";i:1;}',
  'date' => '2014-05-25 16:43:02 +0000',
  'alias_url' => 'portfolio',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Contact',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '763815fb-9d41-44de-a004-0b02c4e92d8e',
  'type' => 'contact',
  'language' => 'und',
  'created' => 1401020042,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'd8d91e50-d70b-4729-bbc4-fcbe54c03272',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<h3>How To Get In Touch With Me</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
							consequat.</p>
							<h3>Connect With Me</h3>
							<ul class="nav nav-vertical">
								<li><a href="/">Twitter</a></li>
								<li><a href="/">Facebook</a></li>
								<li><a href="/">Flickr</a></li>
							</ul>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<h3>How To Get In Touch With Me</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
							tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,<br />
							quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo<br />
							consequat.</p>
<h3>Connect With Me</h3>
<ul class="nav nav-vertical"><li><a href="/">Twitter</a></li>
<li><a href="/">Facebook</a></li>
<li><a href="/">Flickr</a></li>
</ul>',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 1,
  'data' => 'a:2:{s:7:"contact";i:0;s:7:"overlay";i:1;}',
  'date' => '2014-05-25 12:14:02 +0000',
  'alias_url' => 'contact',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Home',
  'log' => '',
  'status' => 1,
  'comment' => 1,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '88c7eaf8-8711-4148-b4a6-aedf6d3cc094',
  'type' => 'home',
  'language' => 'und',
  'created' => 1400986010,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'ea3ca5f4-7c46-4038-8fcf-11996796c79a',
  'revision_uid' => 1,
  'body' => array(),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 1,
  'data' => 'a:2:{s:7:"contact";i:0;s:7:"overlay";i:1;}',
  'date' => '2014-05-25 02:46:50 +0000',
  'alias_url' => 'home',
);
  $nodes[] = array(
  'uid' => 1,
  'title' => 'Project',
  'log' => '',
  'status' => 1,
  'comment' => 2,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '2eb932dd-31ff-4f46-b12f-8436cf14c71f',
  'type' => 'project',
  'language' => 'und',
  'created' => 1401033267,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => 'f335a579-e8fd-4169-a790-5f80aa522dfa',
  'revision_uid' => 1,
  'body' => array(
    'und' => array(
      0 => array(
        'value' => '<div class="col-sm-12 col-md-8">
				<div class="row">
					<div class="col-sm-12 portfolio-large"><img src="/sites/default/files/designssquare_theme/espresso/img/snail-lg.jpg" alt="Placeholder" class="thumbnail img-responsive"></div>
				</div>
				<div class="row hidden-sm">
					<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/birdgreen-lg.jpg" alt="Placeholder" class="thumbnail img-responsive"></a>
					</div>
					<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/leaves-lg.jpg" alt="Placeholder" class="thumbnail img-responsive"></a>
					</div>
					<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/flowers-lg.jpg" alt="Placeholder" class="thumbnail img-responsive"></a>
					</div>
					<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/birdfat-lg.jpg" alt="Placeholder" class="thumbnail img-responsive"></a>
					</div>
				</div>
			</div>
			<div class="col-sm-12 col-md-3 project-info">
				<ul class="pager">
				  <li class="previous">
				    <a href="#">&larr; Previous</a>
				  </li>
				  <li class="next">
				    <a href="#">Next &rarr;</a>
				  </li>
				</ul>
				<h2>Your Project Title</h2>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
				<p><i class="icon-list icon-white"></i> <strong>Categories:</strong> <a href="/">Books</a></p>
				<p><i class="icon-tag icon-white"></i> <strong>Tags:</strong> <a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></p>
			</div>',
        'summary' => '',
        'format' => 'full_html',
        'safe_value' => '<div class="col-sm-12 col-md-8">
<div class="row">
<div class="col-sm-12 portfolio-large"><img src="/sites/default/files/designssquare_theme/espresso/img/snail-lg.jpg" alt="Placeholder" class="thumbnail img-responsive" /></div>
</div>
<div class="row hidden-sm">
<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/birdgreen-lg.jpg" alt="Placeholder" class="thumbnail img-responsive" /></a>
					</div>
<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/leaves-lg.jpg" alt="Placeholder" class="thumbnail img-responsive" /></a>
					</div>
<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/flowers-lg.jpg" alt="Placeholder" class="thumbnail img-responsive" /></a>
					</div>
<div class="col-sm-3 portfolio-thumb-small">
						<a href="#"><img src="/sites/default/files/designssquare_theme/espresso/img/birdfat-lg.jpg" alt="Placeholder" class="thumbnail img-responsive" /></a>
					</div>
</div>
</div>
<div class="col-sm-12 col-md-3 project-info">
<ul class="pager"><li class="previous">
				    <a href="#">← Previous</a>
				  </li>
<li class="next">
				    <a href="#">Next →</a>
				  </li>
</ul><h2>Your Project Title</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod<br />
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,<br />
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo<br />
				consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse<br />
				cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non<br />
				proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
<p><i class="icon-list icon-white"></i> <strong>Categories:</strong> <a href="/">Books</a></p>
<p><i class="icon-tag icon-white"></i> <strong>Tags:</strong> <a href="/">green</a>, <a href="/">stories</a>, <a href="/">fantasy</a></p>
</div>
',
        'safe_summary' => '',
      ),
    ),
  ),
  'rdf_mapping' => array(
    'rdftype' => array(
      0 => 'sioc:Item',
      1 => 'foaf:Document',
    ),
    'title' => array(
      'predicates' => array(
        0 => 'dc:title',
      ),
    ),
    'created' => array(
      'predicates' => array(
        0 => 'dc:date',
        1 => 'dc:created',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'changed' => array(
      'predicates' => array(
        0 => 'dc:modified',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
    'body' => array(
      'predicates' => array(
        0 => 'content:encoded',
      ),
    ),
    'uid' => array(
      'predicates' => array(
        0 => 'sioc:has_creator',
      ),
      'type' => 'rel',
    ),
    'name' => array(
      'predicates' => array(
        0 => 'foaf:name',
      ),
    ),
    'comment_count' => array(
      'predicates' => array(
        0 => 'sioc:num_replies',
      ),
      'datatype' => 'xsd:integer',
    ),
    'last_activity' => array(
      'predicates' => array(
        0 => 'sioc:last_activity_date',
      ),
      'datatype' => 'xsd:dateTime',
      'callback' => 'date_iso8601',
    ),
  ),
  'cid' => 0,
  'last_comment_name' => NULL,
  'last_comment_uid' => 1,
  'comment_count' => 0,
  'name' => 'admin',
  'picture' => 1,
  'data' => 'a:2:{s:7:"contact";i:0;s:7:"overlay";i:1;}',
  'date' => '2014-05-25 15:54:27 +0000',
  'alias_url' => 'project',
);
  return $nodes;
}
