<?php
/**
 * @file
 * designssquare_com_theme_espresso_sample_data.features.inc
 */

/**
 * Implements hook_content_assets_default_settings().
 */
function designssquare_com_theme_espresso_sample_data_content_assets_default_settings() {
$content_assets = array();

$content_assets = array(
  'public://avatar.jpg' => array(
    'uri' => 'public://avatar.jpg',
    'filename' => 'avatar.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/001.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/001.jpg',
    'filename' => '001.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/002.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/002.jpg',
    'filename' => '002.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/003.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/003.jpg',
    'filename' => '003.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/004.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/004.jpg',
    'filename' => '004.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/005.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/005.jpg',
    'filename' => '005.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/006.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/006.jpg',
    'filename' => '006.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/007.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/007.jpg',
    'filename' => '007.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/008.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/008.jpg',
    'filename' => '008.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/009.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/009.jpg',
    'filename' => '009.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/010.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/010.jpg',
    'filename' => '010.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/011.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/011.jpg',
    'filename' => '011.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/012.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/012.jpg',
    'filename' => '012.jpg',
  ),
  'public://designssquare_theme/espresso/bg_img/background.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/bg_img/background.jpg',
    'filename' => 'background.jpg',
  ),
  'public://designssquare_theme/espresso/img/bio-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/bio-lg.jpg',
    'filename' => 'bio-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/bio.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/bio.jpg',
    'filename' => 'bio.jpg',
  ),
  'public://designssquare_theme/espresso/img/birdfat-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/birdfat-lg.jpg',
    'filename' => 'birdfat-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/birdgreen-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/birdgreen-lg.jpg',
    'filename' => 'birdgreen-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/birdretro-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/birdretro-lg.jpg',
    'filename' => 'birdretro-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/birdsepia-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/birdsepia-lg.jpg',
    'filename' => 'birdsepia-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/butterfly-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/butterfly-lg.jpg',
    'filename' => 'butterfly-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/flowers-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/flowers-lg.jpg',
    'filename' => 'flowers-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/glyphicons-halflings-white.png' => array(
    'uri' => 'public://designssquare_theme/espresso/img/glyphicons-halflings-white.png',
    'filename' => 'glyphicons-halflings-white.png',
  ),
  'public://designssquare_theme/espresso/img/glyphicons-halflings.png' => array(
    'uri' => 'public://designssquare_theme/espresso/img/glyphicons-halflings.png',
    'filename' => 'glyphicons-halflings.png',
  ),
  'public://designssquare_theme/espresso/img/gravatar-icon.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/gravatar-icon.jpg',
    'filename' => 'gravatar-icon.jpg',
  ),
  'public://designssquare_theme/espresso/img/leaves-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/leaves-lg.jpg',
    'filename' => 'leaves-lg.jpg',
  ),
  'public://designssquare_theme/espresso/img/slice.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/slice.jpg',
    'filename' => 'slice.jpg',
  ),
  'public://designssquare_theme/espresso/img/snail-lg.jpg' => array(
    'uri' => 'public://designssquare_theme/espresso/img/snail-lg.jpg',
    'filename' => 'snail-lg.jpg',
  ),
  'public://img-espresso-theme/001.jpg' => array(
    'uri' => 'public://img-espresso-theme/001.jpg',
    'filename' => '001.jpg',
  ),
  'public://img-espresso-theme/002.jpg' => array(
    'uri' => 'public://img-espresso-theme/002.jpg',
    'filename' => '002.jpg',
  ),
  'public://img-espresso-theme/003.jpg' => array(
    'uri' => 'public://img-espresso-theme/003.jpg',
    'filename' => '003.jpg',
  ),
  'public://img-espresso-theme/004.jpg' => array(
    'uri' => 'public://img-espresso-theme/004.jpg',
    'filename' => '004.jpg',
  ),
  'public://img-espresso-theme/005.jpg' => array(
    'uri' => 'public://img-espresso-theme/005.jpg',
    'filename' => '005.jpg',
  ),
  'public://img-espresso-theme/006.jpg' => array(
    'uri' => 'public://img-espresso-theme/006.jpg',
    'filename' => '006.jpg',
  ),
  'public://img-espresso-theme/007.jpg' => array(
    'uri' => 'public://img-espresso-theme/007.jpg',
    'filename' => '007.jpg',
  ),
  'public://img-espresso-theme/008.jpg' => array(
    'uri' => 'public://img-espresso-theme/008.jpg',
    'filename' => '008.jpg',
  ),
  'public://img-espresso-theme/009.jpg' => array(
    'uri' => 'public://img-espresso-theme/009.jpg',
    'filename' => '009.jpg',
  ),
  'public://img-espresso-theme/010.jpg' => array(
    'uri' => 'public://img-espresso-theme/010.jpg',
    'filename' => '010.jpg',
  ),
  'public://img-espresso-theme/011.jpg' => array(
    'uri' => 'public://img-espresso-theme/011.jpg',
    'filename' => '011.jpg',
  ),
  'public://img-espresso-theme/012.jpg' => array(
    'uri' => 'public://img-espresso-theme/012.jpg',
    'filename' => '012.jpg',
  ),
  'public://img-espresso-theme/background.jpg' => array(
    'uri' => 'public://img-espresso-theme/background.jpg',
    'filename' => 'background.jpg',
  ),
  'public://img-espresso-theme/bio-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/bio-lg.jpg',
    'filename' => 'bio-lg.jpg',
  ),
  'public://img-espresso-theme/bio.jpg' => array(
    'uri' => 'public://img-espresso-theme/bio.jpg',
    'filename' => 'bio.jpg',
  ),
  'public://img-espresso-theme/birdfat-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/birdfat-lg.jpg',
    'filename' => 'birdfat-lg.jpg',
  ),
  'public://img-espresso-theme/birdgreen-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/birdgreen-lg.jpg',
    'filename' => 'birdgreen-lg.jpg',
  ),
  'public://img-espresso-theme/birdretro-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/birdretro-lg.jpg',
    'filename' => 'birdretro-lg.jpg',
  ),
  'public://img-espresso-theme/birdsepia-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/birdsepia-lg.jpg',
    'filename' => 'birdsepia-lg.jpg',
  ),
  'public://img-espresso-theme/butterfly-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/butterfly-lg.jpg',
    'filename' => 'butterfly-lg.jpg',
  ),
  'public://img-espresso-theme/flowers-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/flowers-lg.jpg',
    'filename' => 'flowers-lg.jpg',
  ),
  'public://img-espresso-theme/glyphicons-halflings-white.png' => array(
    'uri' => 'public://img-espresso-theme/glyphicons-halflings-white.png',
    'filename' => 'glyphicons-halflings-white.png',
  ),
  'public://img-espresso-theme/glyphicons-halflings.png' => array(
    'uri' => 'public://img-espresso-theme/glyphicons-halflings.png',
    'filename' => 'glyphicons-halflings.png',
  ),
  'public://img-espresso-theme/gravatar-icon.jpg' => array(
    'uri' => 'public://img-espresso-theme/gravatar-icon.jpg',
    'filename' => 'gravatar-icon.jpg',
  ),
  'public://img-espresso-theme/leaves-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/leaves-lg.jpg',
    'filename' => 'leaves-lg.jpg',
  ),
  'public://img-espresso-theme/slice.jpg' => array(
    'uri' => 'public://img-espresso-theme/slice.jpg',
    'filename' => 'slice.jpg',
  ),
  'public://img-espresso-theme/snail-lg.jpg' => array(
    'uri' => 'public://img-espresso-theme/snail-lg.jpg',
    'filename' => 'snail-lg.jpg',
  ),
  'public://styles/thumbnail/public/pictures/picture-1-1401076659.jpg' => array(
    'uri' => 'public://styles/thumbnail/public/pictures/picture-1-1401076659.jpg',
    'filename' => 'picture-1-1401076659.jpg',
  ),
);
return $content_assets;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function designssquare_com_theme_espresso_sample_data_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "context" && $api == "context") {
    return array("version" => "3");
  }
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_menu_alias_default_settings().
 */
function designssquare_com_theme_espresso_sample_data_menu_alias_default_settings() {
$menu_alias = array();

$menu_alias = array(
  'main-menu' => array(
    'definition' => array(
      'menu_name' => 'main-menu',
      'title' => 'Main menu',
      'description' => 'The <em>Main</em> menu is used on many sites to show the major sections of the site, often in a top navigation bar.',
    ),
    'links' => array(
      'home' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'home',
        'link_title' => 'Home',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 0,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'home',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'blog-posts' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'blog-posts',
        'link_title' => 'Blog',
        'options' => array(
          'attributes' => array(),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 1,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'blog-posts',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'portfolio' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'portfolio',
        'link_title' => 'Portfolio',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 2,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'portfolio',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'about' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'about',
        'link_title' => 'About',
        'options' => array(
          'attributes' => array(),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 4,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'about',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'contact' => array(
        'menu_name' => 'main-menu',
        'plid' => 0,
        'link_path' => 'contact',
        'link_title' => 'Contact',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 5,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'contact',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
    ),
  ),
  'menu-bottom-menu' => array(
    'definition' => array(
      'menu_name' => 'menu-bottom-menu',
      'title' => 'Bottom Menu',
      'description' => 'menu at the bottom of the page',
    ),
    'links' => array(
      'contact' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'contact',
        'link_title' => 'Contact',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 2,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'contact',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'about' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'about',
        'link_title' => 'About',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 3,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'about',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'portfolio' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'portfolio',
        'link_title' => 'Portfolio',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 4,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'portfolio',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'blog-posts' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'blog-posts',
        'link_title' => 'Blog',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 5,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'blog-posts',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
      'home' => array(
        'menu_name' => 'menu-bottom-menu',
        'plid' => 0,
        'link_path' => 'home',
        'link_title' => 'Home',
        'options' => array(
          'attributes' => array(
            'title' => '',
          ),
        ),
        'module' => 'menu',
        'hidden' => 0,
        'external' => 0,
        'has_children' => 0,
        'expanded' => 0,
        'weight' => 6,
        'depth' => 1,
        'customized' => 1,
        'p1' => 'home',
        'p2' => 0,
        'p3' => 0,
        'p4' => 0,
        'p5' => 0,
        'p6' => 0,
        'p7' => 0,
        'p8' => 0,
        'p9' => 0,
        'updated' => 0,
      ),
    ),
  ),
);
return $menu_alias;
}

/**
 * Implements hook_node_info().
 */
function designssquare_com_theme_espresso_sample_data_node_info() {
  $items = array(
    'basic_page_3_columns' => array(
      'name' => t('Basic Page - 3 Columns'),
      'base' => 'node_content',
      'description' => t('basic page with three columns layout'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'contact' => array(
      'name' => t('Contact'),
      'base' => 'node_content',
      'description' => t('contact layout with a contact form'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'home' => array(
      'name' => t('Home'),
      'base' => 'node_content',
      'description' => t('home / landing page'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'page' => array(
      'name' => t('Basic page'),
      'base' => 'node_content',
      'description' => t('Use <em>basic pages</em> for your static content, such as an \'About us\' page.'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'portfolio' => array(
      'name' => t('Portfolio'),
      'base' => 'node_content',
      'description' => t('layout for portfolio'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
    'project' => array(
      'name' => t('Project'),
      'base' => 'node_content',
      'description' => t('layout for Project page'),
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  return $items;
}

/**
 * Implements hook_strongarm_override_default_settings().
 */
function designssquare_com_theme_espresso_sample_data_strongarm_override_default_settings() {
$strongarm_override = array();

$strongarm_override[] = array(
  'name' => 'site_403',
  'value' => '',
);
$strongarm_override[] = array(
  'name' => 'site_404',
  'value' => '',
);
$strongarm_override[] = array(
  'name' => 'site_frontpage',
  'value' => 'home',
);
$strongarm_override[] = array(
  'name' => 'site_name',
  'value' => 'Espresso Theme',
);
$strongarm_override[] = array(
  'name' => 'site_slogan',
  'value' => 'A clean, minimal, responsive blog &amp; portfolio theme for businesses &amp; creatives',
);
return $strongarm_override;
}
